name: Create package

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "TODO.md"
      - "LICENSE"
      - "jest.config.cjs"
      - ".prettierrc.json"
      - ".prettierignore"
      - ".gitignore"
      - ".eslintrc.cjs"
      - "tsconfig.json"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for bumping version
      id-token: write # Required for OIDC for npm
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org/"

      - name: Setup git config
        run: |
          git config --global user.name "skedwards88"
          git config --global user.email "skedwards88@gmail.com"

      - run: npm ci

      - run: npm test

      - run: npm run build

      - name: Bump version
        run: npm version patch

      - name: Push
        run: |
          git push origin main

      - run: npm publish --access public
